<a href="https://colab.research.google.com/github/icarocarmona/pos-tech-dtat/blob/main/f3_big_data/SimpleRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import scipy
from scipy import stats
import numpy as np

In [ ]:
matrix = np.array([[8,0,3,4,6],[5,6,1,8,9],[8,0,0,5,10]])
newUser = [8,0,2,3,0]
unattended = [0,1,0,0,1]
print(matrix)
movies_name = ['Round 6', 'A Invocação do Mal', '9 Desconhecidos', 'You', 'La Casa de Papel']

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  0  5 10]]


In [ ]:
similarity = [0]* 3
print(matrix[0][0])
print(matrix[1][0])
print(matrix[1,:])
# para cada usuário do sistema..
for i in range(0,3):
  #vamor pegar os dados desse usuário
  temp = matrix[i,:]
  print (i, temp)
  # mas queremos apenas comparar os dados que o novo usuario assistiu (ou seja.. newUser != 0)
  tempUser = [t for n, t in zip(newUser, temp) if n != 0]
  tempNewUser = [ n for n in newUser if n!= 0]

  #para verificar o processo
  print('user:', i )
  print(temp, tempNewUser)

  # vamos usar a biblioteca scipy.stats que ja calcula a pearson!!
  similarity[i] = scipy.stats.pearsonr(tempUser, tempNewUser)[0]
print()

print(similarity)

8
5
[5 6 1 8 9]
0 [8 0 3 4 6]
user: 0
[8 0 3 4 6] [8, 2, 3]
1 [5 6 1 8 9]
user: 1
[5 6 1 8 9] [8, 2, 3]
2 [ 8  0  0  5 10]
user: 2
[ 8  0  0  5 10] [8, 2, 3]

[0.9994237971287663, 0.23621543814299698, 0.8723686098443353]


In [ ]:
nota_peso = np.zeros((3,5))
for nUser in range(3):
  for nFilme in range(5):
    print('nota_peso[',nUser, '][',nFilme, '] = , unattended[',nFilme, '], * ,matrix[',nUser,'][',nFilme, '], * similarity[',nUser,']')
    print('nota_peso[',nUser, '][',nFilme, '] = ', unattended[nFilme], ' * ' ,matrix[nUser][nFilme], ' * ', similarity[nUser])
    nota_peso[nUser][nFilme] = unattended[nFilme] * matrix[nUser][nFilme] * similarity[nUser]
    print(nota_peso)


nota_peso[ 0 ][ 0 ] = , unattended[ 0 ], * ,matrix[ 0 ][ 0 ], * similarity[ 0 ]
nota_peso[ 0 ][ 0 ] =  0  *  8  *  0.9994237971287663
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
nota_peso[ 0 ][ 1 ] = , unattended[ 1 ], * ,matrix[ 0 ][ 1 ], * similarity[ 0 ]
nota_peso[ 0 ][ 1 ] =  1  *  0  *  0.9994237971287663
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
nota_peso[ 0 ][ 2 ] = , unattended[ 2 ], * ,matrix[ 0 ][ 2 ], * similarity[ 0 ]
nota_peso[ 0 ][ 2 ] =  0  *  3  *  0.9994237971287663
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
nota_peso[ 0 ][ 3 ] = , unattended[ 3 ], * ,matrix[ 0 ][ 3 ], * similarity[ 0 ]
nota_peso[ 0 ][ 3 ] =  0  *  4  *  0.9994237971287663
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
nota_peso[ 0 ][ 4 ] = , unattended[ 4 ], * ,matrix[ 0 ][ 4 ], * similarity[ 0 ]
nota_peso[ 0 ][ 4 ] =  1  *  6  *  0.9994237971287663
[[0.         0.         0.         0.         5.99654278]
 [0.         0.         0.         0.         0.    

In [ ]:
notas_acumuladas = np.sum(nota_peso.T,axis=1)
print(notas_acumuladas)


[ 0.          1.41729263  0.          0.         16.84616782]


In [ ]:
temp_peso = nota_peso
temp_peso[nota_peso > 0] = 1
print(temp_peso)
temp_similaridade = np.zeros((3,5))
for nUser in range(3):
  for nFilme in range(5):
    temp_similaridade[nUser][nFilme] = temp_peso[nUser][nFilme] * similarity[nUser]
    print(temp_similaridade)
    similaridade_acumulada = np.sum(temp_similaridade.T,axis=1)
    print(similaridade_acumulada)


[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0.        0.        0.        0.        0.9994238]
 [0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.       ]]
[0.        0.        0.        0.        0.9994238]
[[0.        0.        0.        0.        0.9994238]
 [0.        0.        0.        0.        0.       ]
 [0.        0.        0.        0.        0.       ]]
[0.        0.        0.        0.        0.9994238]
[[0.         0.         0.         0.         0.9994238 ]
 [0.         0.23621544 0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]
[0.         0.23621544 0.         0.         0.9994238 ]
[

In [ ]:
nota_final =[0] * 5
#agora a normalização para cada filme com nota acumulada, eu normalizo pela soma dos pesos (similaridade)
for nFilme in range(5):
  if(similaridade_acumulada[nFilme] > 0):
    nota_final[nFilme] = notas_acumuladas[nFilme] / similaridade_acumulada[nFilme]
  else:
    nota_final[nFilme] = 0

print(nota_final)


[0, 6.0, 0, 0, 7.991510972567143]


In [ ]:
nAssistidos = sum(unattended)
notasOrdenadasIndex = sorted(range(len(nota_final)),key=nota_final.__getitem__)[::-1][0:nAssistidos]
print(notasOrdenadasIndex)
for i in notasOrdenadasIndex:
  print(movies_name[i], 'nota: ', nota_final[i])


[4, 1]
La Casa de Papel nota:  7.991510972567143
A Invocação do Mal nota:  6.0
